export const TEAM_CREATE_REQUEST = 'TEAM_CREATE_REQUEST'
export const TEAM_CREATE_SUCCESS = 'TEAM_CREATE_SUCCESS'
export const TEAM_CREATE_FAIL = 'TEAM_CREATE_FAIL'

export const TEAM_GET_ONE_REQUEST = 'TEAM_GET_ONE_REQUEST'
export const TEAM_GET_ONE_SUCCESS = 'TEAM_GET_ONE_SUCCESS'
export const TEAM_GET_ONE_FAIL = 'TEAM_GET_ONE_FAIL'

export const TEAM_UPDATE_REQUEST = 'TEAM_UPDATE_REQUEST'
export const TEAM_UPDATE_SUCCESS = 'TEAM_UPDATE_SUCCESS'
export const TEAM_UPDATE_FAIL = 'TEAM_UPDATE_FAIL'
